{% set version = "5.7.3" %}

package:
  name: typescript
  version: {{ version }}

source:
  url: https://registry.npmjs.org/typescript/-/typescript-{{ version }}.tgz
  sha256: 80cfca1254bab8e81d639178e42d6406d856fba6e34cad60d1ab50ee6e5f7ebb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs
  
test:
  commands:
    - tsc --help
   
about:
  home: https://github.com/Microsoft/TypeScript
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.'
  description: |
    TypeScript is a language for application-scale JavaScript. TypeScript adds 
    optional types, classes, and modules to JavaScript. TypeScript supports 
    tools for large-scale JavaScript applications for any browser, for any 
    host, on any OS. TypeScript compiles to readable, standards-based JavaScript. 
    Try it out at the playground, and stay up to date via our blog and Twitter account.
  doc_url: https://www.typescriptlang.org/docs/
  dev_url: https://github.com/Microsoft/TypeScript
  
extra:
  recipe-maintainers:
    - cshaley
    - danielnachun
    - sannykr
