{% set name = "typescript" %}
{% set version = "3.6.5" %}
{% set sha256 = "e846ab11d24938709f4a4dd49b8f11ca9a47c74a01c6491b6b9cd145e3205e4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Microsoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g typescript
  requires:
    - nodejs
   
about:
  home: https://github.com/Microsoft/TypeScript
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.'
  description: |
    TypeScript is a language for application-scale JavaScript. TypeScript adds 
    optional types, classes, and modules to JavaScript. TypeScript supports 
    tools for large-scale JavaScript applications for any browser, for any 
    host, on any OS. TypeScript compiles to readable, standards-based JavaScript. 
    Try it out at the playground, and stay up to date via our blog and Twitter account.
  doc_url: https://www.typescriptlang.org/docs/
  dev_url: https://github.com/Microsoft/TypeScript
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
